/***************************************************************************//**
* \file IfxLPCOMP_regdef.h
*
* \brief
* LPCOMP Registers
*
********************************************************************************
* \copyright
* (c) 2025-2026, Infineon Technologies AG or an affiliate of
* Infineon Technologies AG.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
********************************************************************************
*
* \defgroup IfxSfr_LPCOMP_Registers LPCOMP Registers
* \ingroup IfxSfr
* \defgroup IfxSfr_LPCOMP_Registers_Bitfields Bitfields
* \ingroup IfxSfr_LPCOMP_Registers
*
* \defgroup IfxSfr_LPCOMP_Registers_union Register unions
* \ingroup IfxSfr_LPCOMP_Registers
*
* \defgroup IfxSfr_LPCOMP_Registers_struct Memory map
* \ingroup IfxSfr_LPCOMP_Registers
*
*******************************************************************************/

#ifndef _IFXLPCOMP_REGDEF_H_
#define _IFXLPCOMP_REGDEF_H_ 1

/******************************************************************************/
#include "Ifx_TypesReg.h"
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/


/** \addtogroup IfxSfr_LPCOMP_Registers_Bitfields
 * \{  */
/** \brief LPCOMP Configuration Register */
typedef struct _Ifx_LPCOMP_CONFIG_Bits
{
    __I  Ifx_UReg_32Bit :30;                    /**< \brief [29:0]  \internal Reserved */
    __IO Ifx_UReg_32Bit LPREF_EN:1;             /**< \brief [30:30] Enable the local reference generator
                                                                    circuit to generate the local Vref and Ibias.
                                                                    Ibias current is an  alternative to the reference
                                                                    current IREF generated by SRSS.
                                                                    This bit must be set for System Deep Sleep and
                                                                    System Hibernate operation. (rw) */
    __IO Ifx_UReg_32Bit ENABLED:1;              /**< \brief [31:31] - 0: LPCOMP disabled (puts analog in power
                                                                    down, opens all switches, all clocks turned off)
                                                                    - 1: LPCOMP enabled (rw) */
} Ifx_LPCOMP_CONFIG_Bits;

/** \brief LPCOMP Status Register */
typedef struct _Ifx_LPCOMP_STATUS_Bits
{
    __I  Ifx_UReg_32Bit OUT0:1;                 /**< \brief [0:0]   Current output value of the comparator 0. (r) */
    __I  Ifx_UReg_32Bit :15;                    /**< \brief [15:1]  \internal Reserved */
    __I  Ifx_UReg_32Bit OUT1:1;                 /**< \brief [16:16] Current output value of the comparator 1. (r) */
    __I  Ifx_UReg_32Bit :15;                    /**< \brief [31:17] \internal Reserved */
} Ifx_LPCOMP_STATUS_Bits;

/** \brief LPCOMP Interrupt request register */
typedef struct _Ifx_LPCOMP_INTR_Bits
{
    __IO Ifx_UReg_32Bit COMP0:1;                /**< \brief [0:0]   Comparator 0 Interrupt: hardware sets this
                                                                    interrupt when comparator 0 triggers.
                                                                    Write with '1' to clear bit. (rw) */
    __IO Ifx_UReg_32Bit COMP1:1;                /**< \brief [1:1]   Comparator 1 Interrupt: hardware sets this
                                                                    interrupt when comparator 1 triggers.
                                                                    Write with '1' to clear bit. (rw) */
    __I  Ifx_UReg_32Bit :30;                    /**< \brief [31:2]  \internal Reserved */
} Ifx_LPCOMP_INTR_Bits;

/** \brief LPCOMP Interrupt set register */
typedef struct _Ifx_LPCOMP_INTR_SET_Bits
{
    __IO Ifx_UReg_32Bit COMP0:1;                /**< \brief [0:0]   Write with '1' to set corresponding bit in
                                                                    interrupt request register. (rw) */
    __IO Ifx_UReg_32Bit COMP1:1;                /**< \brief [1:1]   Write with '1' to set corresponding bit in
                                                                    interrupt request register. (rw) */
    __I  Ifx_UReg_32Bit :30;                    /**< \brief [31:2]  \internal Reserved */
} Ifx_LPCOMP_INTR_SET_Bits;

/** \brief LPCOMP Interrupt request mask */
typedef struct _Ifx_LPCOMP_INTR_MASK_Bits
{
    __IO Ifx_UReg_32Bit COMP0_MASK:1;           /**< \brief [0:0]   Mask bit for corresponding bit in interrupt
                                                                    request register. (rw) */
    __IO Ifx_UReg_32Bit COMP1_MASK:1;           /**< \brief [1:1]   Mask bit for corresponding bit in interrupt
                                                                    request register. (rw) */
    __I  Ifx_UReg_32Bit :30;                    /**< \brief [31:2]  \internal Reserved */
} Ifx_LPCOMP_INTR_MASK_Bits;

/** \brief LPCOMP Interrupt request masked */
typedef struct _Ifx_LPCOMP_INTR_MASKED_Bits
{
    __I  Ifx_UReg_32Bit COMP0_MASKED:1;         /**< \brief [0:0]   Logical and of corresponding request and mask bits. (r) */
    __I  Ifx_UReg_32Bit COMP1_MASKED:1;         /**< \brief [1:1]   Logical and of corresponding request and mask bits. (r) */
    __I  Ifx_UReg_32Bit :30;                    /**< \brief [31:2]  \internal Reserved */
} Ifx_LPCOMP_INTR_MASKED_Bits;

/** \brief Comparator 0 control Register */
typedef struct _Ifx_LPCOMP_CMP0_CTRL_Bits
{
    __IO Ifx_UReg_32Bit MODE0:2;                /**< \brief [1:0]    (rw)
                                                OFF           : 0u   Off
                                                ULP           : 1u   Ultra lowpower operating mode (uses less power, <
                                                                    300nA), must be used for DeepSleep or Hibernate.
                                                                    Only in this mode a local iref will be used.
                                                LP            : 2u   Low Power operating mode (uses more power, <10uA @@@ TBD).
                                                                    In this mode the iref from SRSS will be used.
                                                NORMAL        : 3u   Normal, full speed power operating mode (uses <150uA).
                                                                    In this mode the iref from SRSS will be used. */
    __I  Ifx_UReg_32Bit :3;                     /**< \brief [4:2]   \internal Reserved */
    __IO Ifx_UReg_32Bit HYST0:1;                /**< \brief [5:5]   Add hysteresis to the comparator
                                                                    0= Disable Hysteresis
                                                                    1= Enable Hysteresis (rw) */
    __IO Ifx_UReg_32Bit INTTYPE0:2;             /**< \brief [7:6]    (rw)
                                                DISABLE       : 0u   Disabled, no interrupts will be detected
                                                RISING        : 1u   Rising edge
                                                FALLING       : 2u   Falling edge
                                                BOTH          : 3u   Both rising and falling edges */
    __I  Ifx_UReg_32Bit :2;                     /**< \brief [9:8]   \internal Reserved */
    __IO Ifx_UReg_32Bit DSI_BYPASS0:1;          /**< \brief [10:10] Asynchronous: bypass comparator output
                                                                    synchronization:
                                                                    0=synchronize (level or pulse)
                                                                    1=bypass (output async)
                                                                    Note that in System Deep Sleep mode, this bit needs
                                                                    to be set to observe the output on the dedicated pin. (rw) */
    __IO Ifx_UReg_32Bit DSI_LEVEL0:1;           /**< \brief [11:11] Synchronous comparator output (trigger):
                                                                    0=pulse
                                                                    1=level (rw) */
    __I  Ifx_UReg_32Bit :20;                    /**< \brief [31:12] \internal Reserved */
} Ifx_LPCOMP_CMP0_CTRL_Bits;

/* LPCOMP_CMP0_CTRL.MODE0 enumerated values */

/** \brief Off */
#define IFX_LPCOMP_CMP0_CTRL_MODE0_OFF (0u)

/** \brief Ultra lowpower operating mode (uses less power, < 300nA), must be used for
DeepSleep or Hibernate. Only in this mode a local iref will be used. */
#define IFX_LPCOMP_CMP0_CTRL_MODE0_ULP (1u)

/** \brief Low Power operating mode (uses more power, <10uA @@@ TBD).
In this mode the iref from SRSS will be used. */
#define IFX_LPCOMP_CMP0_CTRL_MODE0_LP (2u)

/** \brief Normal, full speed power operating mode (uses <150uA).
In this mode the iref from SRSS will be used. */
#define IFX_LPCOMP_CMP0_CTRL_MODE0_NORMAL (3u)

/* LPCOMP_CMP0_CTRL.INTTYPE0 enumerated values */

/** \brief Disabled, no interrupts will be detected */
#define IFX_LPCOMP_CMP0_CTRL_INTTYPE0_DISABLE (0u)

/** \brief Rising edge */
#define IFX_LPCOMP_CMP0_CTRL_INTTYPE0_RISING (1u)

/** \brief Falling edge */
#define IFX_LPCOMP_CMP0_CTRL_INTTYPE0_FALLING (2u)

/** \brief Both rising and falling edges */
#define IFX_LPCOMP_CMP0_CTRL_INTTYPE0_BOTH (3u)

/** \brief Comparator 0 switch control */
typedef struct _Ifx_LPCOMP_CMP0_SW_Bits
{
    __IO Ifx_UReg_32Bit CMP0_IP0:1;             /**< \brief [0:0]   Comparator 0 positive terminal isolation
                                                                    switch to GPIO (rw) */
    __IO Ifx_UReg_32Bit CMP0_AP0:1;             /**< \brief [1:1]   Comparator 0 positive terminal  switch to
                                                                    amuxbusA (rw) */
    __IO Ifx_UReg_32Bit CMP0_BP0:1;             /**< \brief [2:2]   Comparator 0 positive terminal  switch to
                                                                    amuxbusB (rw) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [3:3]   \internal Reserved */
    __IO Ifx_UReg_32Bit CMP0_IN0:1;             /**< \brief [4:4]   Comparator 0 negative terminal isolation
                                                                    switch to GPIO (rw) */
    __IO Ifx_UReg_32Bit CMP0_AN0:1;             /**< \brief [5:5]   Comparator 0 negative terminal  switch to
                                                                    amuxbusA (rw) */
    __IO Ifx_UReg_32Bit CMP0_BN0:1;             /**< \brief [6:6]   Comparator 0 negative terminal  switch to
                                                                    amuxbusB (rw) */
    __IO Ifx_UReg_32Bit CMP0_VN0:1;             /**< \brief [7:7]   Comparator 0 negative terminal  switch to
                                                                    local Vref  (LPREF_EN must be set) (rw) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_LPCOMP_CMP0_SW_Bits;

/** \brief Comparator 0 switch control clear */
typedef struct _Ifx_LPCOMP_CMP0_SW_CLEAR_Bits
{
    __IO Ifx_UReg_32Bit CMP0_IP0:1;             /**< \brief [0:0]   see corresponding bit in CMP0_SW (rw) */
    __IO Ifx_UReg_32Bit CMP0_AP0:1;             /**< \brief [1:1]   see corresponding bit in CMP0_SW (rw) */
    __IO Ifx_UReg_32Bit CMP0_BP0:1;             /**< \brief [2:2]   see corresponding bit in CMP0_SW (rw) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [3:3]   \internal Reserved */
    __IO Ifx_UReg_32Bit CMP0_IN0:1;             /**< \brief [4:4]   see corresponding bit in CMP0_SW (rw) */
    __IO Ifx_UReg_32Bit CMP0_AN0:1;             /**< \brief [5:5]   see corresponding bit in CMP0_SW (rw) */
    __IO Ifx_UReg_32Bit CMP0_BN0:1;             /**< \brief [6:6]   see corresponding bit in CMP0_SW (rw) */
    __IO Ifx_UReg_32Bit CMP0_VN0:1;             /**< \brief [7:7]   see corresponding bit in CMP0_SW (rw) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_LPCOMP_CMP0_SW_CLEAR_Bits;

/** \brief Comparator 1 control Register */
typedef struct _Ifx_LPCOMP_CMP1_CTRL_Bits
{
    __IO Ifx_UReg_32Bit MODE1:2;                /**< \brief [1:0]    (rw)
                                                OFF           : 0u   Off
                                                ULP           : 1u   Ultra lowpower operating mode (uses less power, <
                                                                    300nA), must be used for DeepSleep or Hibernate.
                                                                    Only in this mode a local iref will be used.
                                                LP            : 2u   Low Power operating mode (uses more power, <10uA @@@ TBD).
                                                                    In this mode the iref from SRSS will be used.
                                                NORMAL        : 3u   Normal, full speed power operating mode (uses <150uA).
                                                                    In this mode the iref from SRSS will be used. */
    __I  Ifx_UReg_32Bit :3;                     /**< \brief [4:2]   \internal Reserved */
    __IO Ifx_UReg_32Bit HYST1:1;                /**< \brief [5:5]   Add hysteresis to the comparator
                                                                    0= Disable Hysteresis
                                                                    1= Enable Hysteresis (rw) */
    __IO Ifx_UReg_32Bit INTTYPE1:2;             /**< \brief [7:6]    (rw)
                                                DISABLE       : 0u   Disabled, no interrupts will be detected
                                                RISING        : 1u   Rising edge
                                                FALLING       : 2u   Falling edge
                                                BOTH          : 3u   Both rising and falling edges */
    __I  Ifx_UReg_32Bit :2;                     /**< \brief [9:8]   \internal Reserved */
    __IO Ifx_UReg_32Bit DSI_BYPASS1:1;          /**< \brief [10:10] Asynchronous: bypass comparator output
                                                                    synchronization:
                                                                    0=synchronize (level or pulse)
                                                                    1=bypass (output async)
                                                                    Note that in System Deep Sleep mode, this bit needs
                                                                    to be set to observe the output on the dedicated pin. (rw) */
    __IO Ifx_UReg_32Bit DSI_LEVEL1:1;           /**< \brief [11:11] Synchronous comparator output (trigger):
                                                                    0=pulse
                                                                    1=level (rw) */
    __I  Ifx_UReg_32Bit :20;                    /**< \brief [31:12] \internal Reserved */
} Ifx_LPCOMP_CMP1_CTRL_Bits;

/* LPCOMP_CMP1_CTRL.MODE1 enumerated values */

/** \brief Off */
#define IFX_LPCOMP_CMP1_CTRL_MODE1_OFF (0u)

/** \brief Ultra lowpower operating mode (uses less power, < 300nA), must be used for
DeepSleep or Hibernate. Only in this mode a local iref will be used. */
#define IFX_LPCOMP_CMP1_CTRL_MODE1_ULP (1u)

/** \brief Low Power operating mode (uses more power, <10uA @@@ TBD).
In this mode the iref from SRSS will be used. */
#define IFX_LPCOMP_CMP1_CTRL_MODE1_LP (2u)

/** \brief Normal, full speed power operating mode (uses <150uA).
In this mode the iref from SRSS will be used. */
#define IFX_LPCOMP_CMP1_CTRL_MODE1_NORMAL (3u)

/* LPCOMP_CMP1_CTRL.INTTYPE1 enumerated values */

/** \brief Disabled, no interrupts will be detected */
#define IFX_LPCOMP_CMP1_CTRL_INTTYPE1_DISABLE (0u)

/** \brief Rising edge */
#define IFX_LPCOMP_CMP1_CTRL_INTTYPE1_RISING (1u)

/** \brief Falling edge */
#define IFX_LPCOMP_CMP1_CTRL_INTTYPE1_FALLING (2u)

/** \brief Both rising and falling edges */
#define IFX_LPCOMP_CMP1_CTRL_INTTYPE1_BOTH (3u)

/** \brief Comparator 1 switch control */
typedef struct _Ifx_LPCOMP_CMP1_SW_Bits
{
    __IO Ifx_UReg_32Bit CMP1_IP1:1;             /**< \brief [0:0]   Comparator 1 positive terminal isolation
                                                                    switch to GPIO (rw) */
    __IO Ifx_UReg_32Bit CMP1_AP1:1;             /**< \brief [1:1]   Comparator 1 positive terminal  switch to
                                                                    amuxbusA (rw) */
    __IO Ifx_UReg_32Bit CMP1_BP1:1;             /**< \brief [2:2]   Comparator 1 positive terminal  switch to
                                                                    amuxbusB (rw) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [3:3]   \internal Reserved */
    __IO Ifx_UReg_32Bit CMP1_IN1:1;             /**< \brief [4:4]   Comparator 1 negative terminal isolation
                                                                    switch to GPIO (rw) */
    __IO Ifx_UReg_32Bit CMP1_AN1:1;             /**< \brief [5:5]   Comparator 1 negative terminal  switch to
                                                                    amuxbusA (rw) */
    __IO Ifx_UReg_32Bit CMP1_BN1:1;             /**< \brief [6:6]   Comparator 1 negative terminal  switch to
                                                                    amuxbusB (rw) */
    __IO Ifx_UReg_32Bit CMP1_VN1:1;             /**< \brief [7:7]   Comparator 1 negative terminal  switch to
                                                                    local Vref  (LPREF_EN must be set) (rw) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_LPCOMP_CMP1_SW_Bits;

/** \brief Comparator 1 switch control clear */
typedef struct _Ifx_LPCOMP_CMP1_SW_CLEAR_Bits
{
    __IO Ifx_UReg_32Bit CMP1_IP1:1;             /**< \brief [0:0]   see corresponding bit in CMP1_SW (rw) */
    __IO Ifx_UReg_32Bit CMP1_AP1:1;             /**< \brief [1:1]   see corresponding bit in CMP1_SW (rw) */
    __IO Ifx_UReg_32Bit CMP1_BP1:1;             /**< \brief [2:2]   see corresponding bit in CMP1_SW (rw) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [3:3]   \internal Reserved */
    __IO Ifx_UReg_32Bit CMP1_IN1:1;             /**< \brief [4:4]   see corresponding bit in CMP1_SW (rw) */
    __IO Ifx_UReg_32Bit CMP1_AN1:1;             /**< \brief [5:5]   see corresponding bit in CMP1_SW (rw) */
    __IO Ifx_UReg_32Bit CMP1_BN1:1;             /**< \brief [6:6]   see corresponding bit in CMP1_SW (rw) */
    __IO Ifx_UReg_32Bit CMP1_VN1:1;             /**< \brief [7:7]   see corresponding bit in CMP1_SW (rw) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_LPCOMP_CMP1_SW_CLEAR_Bits;


/** \}  */
/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_LPCOMP_Registers_union
 * \{   */
/** \brief LPCOMP Configuration Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_CONFIG_Bits B;                   /**< \brief Bitfield access */
} Ifx_LPCOMP_CONFIG;

/** \brief LPCOMP Status Register */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_STATUS_Bits B;                   /**< \brief Bitfield access */
} Ifx_LPCOMP_STATUS;

/** \brief LPCOMP Interrupt request register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_INTR_Bits B;                     /**< \brief Bitfield access */
} Ifx_LPCOMP_INTR;

/** \brief LPCOMP Interrupt set register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_INTR_SET_Bits B;                 /**< \brief Bitfield access */
} Ifx_LPCOMP_INTR_SET;

/** \brief LPCOMP Interrupt request mask */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_INTR_MASK_Bits B;                /**< \brief Bitfield access */
} Ifx_LPCOMP_INTR_MASK;

/** \brief LPCOMP Interrupt request masked */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_INTR_MASKED_Bits B;              /**< \brief Bitfield access */
} Ifx_LPCOMP_INTR_MASKED;

/** \brief Comparator 0 control Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_CMP0_CTRL_Bits B;                /**< \brief Bitfield access */
} Ifx_LPCOMP_CMP0_CTRL;

/** \brief Comparator 0 switch control */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_CMP0_SW_Bits B;                  /**< \brief Bitfield access */
} Ifx_LPCOMP_CMP0_SW;

/** \brief Comparator 0 switch control clear */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_CMP0_SW_CLEAR_Bits B;            /**< \brief Bitfield access */
} Ifx_LPCOMP_CMP0_SW_CLEAR;

/** \brief Comparator 1 control Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_CMP1_CTRL_Bits B;                /**< \brief Bitfield access */
} Ifx_LPCOMP_CMP1_CTRL;

/** \brief Comparator 1 switch control */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_CMP1_SW_Bits B;                  /**< \brief Bitfield access */
} Ifx_LPCOMP_CMP1_SW;

/** \brief Comparator 1 switch control clear */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_LPCOMP_CMP1_SW_CLEAR_Bits B;            /**< \brief Bitfield access */
} Ifx_LPCOMP_CMP1_SW_CLEAR;


/** \}  */

/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_LPCOMP_struct
 * \{  */
/******************************************************************************/
/** \name Object L0
 * \{  */
/** \brief LPCOMP object */
typedef volatile struct _Ifx_LPCOMP
{
       __IO Ifx_LPCOMP_CONFIG                   CONFIG;                 /**< \brief 0, LPCOMP Configuration Register*/
       __I  Ifx_LPCOMP_STATUS                   STATUS;                 /**< \brief 4, LPCOMP Status Register*/
       __I  Ifx_UReg_8Bit                       reserved_8[8];          /**< \brief 8, */
       __IO Ifx_LPCOMP_INTR                     INTR;                   /**< \brief 10, LPCOMP Interrupt request register*/
       __IO Ifx_LPCOMP_INTR_SET                 INTR_SET;               /**< \brief 14, LPCOMP Interrupt set register*/
       __IO Ifx_LPCOMP_INTR_MASK                INTR_MASK;              /**< \brief 18, LPCOMP Interrupt request mask*/
       __I  Ifx_LPCOMP_INTR_MASKED              INTR_MASKED;            /**< \brief 1C, LPCOMP Interrupt request masked*/
       __I  Ifx_UReg_8Bit                       reserved_20[32];        /**< \brief 20, */
       __IO Ifx_LPCOMP_CMP0_CTRL                CMP0_CTRL;              /**< \brief 40, Comparator 0 control Register*/
       __I  Ifx_UReg_8Bit                       reserved_44[12];        /**< \brief 44, */
       __IO Ifx_LPCOMP_CMP0_SW                  CMP0_SW;                /**< \brief 50, Comparator 0 switch control*/
       __IO Ifx_LPCOMP_CMP0_SW_CLEAR            CMP0_SW_CLEAR;          /**< \brief 54, Comparator 0 switch control clear*/
       __I  Ifx_UReg_8Bit                       reserved_58[40];        /**< \brief 58, */
       __IO Ifx_LPCOMP_CMP1_CTRL                CMP1_CTRL;              /**< \brief 80, Comparator 1 control Register*/
       __I  Ifx_UReg_8Bit                       reserved_84[12];        /**< \brief 84, */
       __IO Ifx_LPCOMP_CMP1_SW                  CMP1_SW;                /**< \brief 90, Comparator 1 switch control*/
       __IO Ifx_LPCOMP_CMP1_SW_CLEAR            CMP1_SW_CLEAR;          /**< \brief 94, Comparator 1 switch control clear*/
       __I  Ifx_UReg_8Bit                       reserved_98[65384];     /**< \brief 98, */
} Ifx_LPCOMP;

/******************************************************************************/

/******************************************************************************/

#endif /* _IFXLPCOMP_REGDEF_H_ */
