/***************************************************************************//**
* \file IfxMXAES_bf.h
*
* \brief
* MXAES Bitfields mask and offset
*
********************************************************************************
* \copyright
* (c) 2025-2026, Infineon Technologies AG or an affiliate of
* Infineon Technologies AG.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
********************************************************************************
*
* \defgroup IfxSfr_MXAES_Registers_BitfieldsMask Bitfields mask and offset
* \ingroup IfxSfr_MXAES_Registers
*
*******************************************************************************/

#ifndef _IFXMXAES_BF_H_
#define _IFXMXAES_BF_H_ 1

/******************************************************************************/

/******************************************************************************/

/** \addtogroup IfxSfr_MXAES_Registers_BitfieldsMask
 * \{  */
/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_Bits.CALC_MODE */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_CALC_MODE_LEN (5u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_Bits.CALC_MODE */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_CALC_MODE_MSK (0x1fu)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_Bits.CALC_MODE */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_CALC_MODE_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_Bits.CRYPT_MODE */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_CRYPT_MODE_LEN (5u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_Bits.CRYPT_MODE */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_CRYPT_MODE_MSK (0x1fu)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_Bits.CRYPT_MODE */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_CRYPT_MODE_OFF (8u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CMD_Bits.START_ENC */
#define IFX_MXAES_UNMASKED_USER_RANGE_CMD_START_ENC_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CMD_Bits.START_ENC */
#define IFX_MXAES_UNMASKED_USER_RANGE_CMD_START_ENC_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CMD_Bits.START_ENC */
#define IFX_MXAES_UNMASKED_USER_RANGE_CMD_START_ENC_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CMD_Bits.START_DEC */
#define IFX_MXAES_UNMASKED_USER_RANGE_CMD_START_DEC_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CMD_Bits.START_DEC */
#define IFX_MXAES_UNMASKED_USER_RANGE_CMD_START_DEC_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CMD_Bits.START_DEC */
#define IFX_MXAES_UNMASKED_USER_RANGE_CMD_START_DEC_OFF (1u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.DATA */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_DATA_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.DATA */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_DATA_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.DATA */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_128LO */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_128LO_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_128LO */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_128LO_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_128LO */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_128LO_OFF (1u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_128HI */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_128HI_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_128HI */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_128HI_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_128HI */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_128HI_OFF (2u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_256 */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_256_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_256 */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_256_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.AES_KEY_256 */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_AES_KEY_256_OFF (4u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.SEC_LEVEL_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_SEC_LEVEL_RR_LEN (4u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.SEC_LEVEL_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_SEC_LEVEL_RR_MSK (0xfu)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.SEC_LEVEL_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_SEC_LEVEL_RR_OFF (8u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.SEED */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_SEED_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.SEED */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_SEED_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.SEED */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_SEED_OFF (13u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.RDY */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_RDY_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.RDY */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_RDY_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.RDY */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_RDY_OFF (14u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.BSY */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_BSY_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.BSY */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_BSY_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.BSY */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_BSY_OFF (15u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.CALC_MODE_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_CALC_MODE_RR_LEN (5u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.CALC_MODE_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_CALC_MODE_RR_MSK (0x1fu)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.CALC_MODE_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_CALC_MODE_RR_OFF (16u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.CRYPT_MODE_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_CRYPT_MODE_RR_LEN (5u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.CRYPT_MODE_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_CRYPT_MODE_RR_MSK (0x1fu)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.CRYPT_MODE_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_CRYPT_MODE_RR_OFF (24u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.START_ENC_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_START_ENC_RR_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.START_ENC_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_START_ENC_RR_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.START_ENC_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_START_ENC_RR_OFF (29u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.START_DEC_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_START_DEC_RR_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.START_DEC_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_START_DEC_RR_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_STAT_Bits.START_DEC_RR */
#define IFX_MXAES_UNMASKED_USER_RANGE_STAT_START_DEC_RR_OFF (30u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_2_Bits.SEC_LEVEL */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_2_SEC_LEVEL_LEN (4u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_2_Bits.SEC_LEVEL */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_2_SEC_LEVEL_MSK (0xfu)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CFG_2_Bits.SEC_LEVEL */
#define IFX_MXAES_UNMASKED_USER_RANGE_CFG_2_SEC_LEVEL_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_CALC_FINISHED_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_CALC_FINISHED_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_CALC_FINISHED_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_SET_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_SET_CALC_FINISHED_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_SET_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_SET_CALC_FINISHED_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_SET_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_SET_CALC_FINISHED_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_MASK_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_MASK_CALC_FINISHED_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_MASK_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_MASK_CALC_FINISHED_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_MASK_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_MASK_CALC_FINISHED_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_MASKED_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_MASKED_CALC_FINISHED_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_MASKED_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_MASKED_CALC_FINISHED_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_INTR_MASKED_Bits.CALC_FINISHED */
#define IFX_MXAES_UNMASKED_USER_RANGE_INTR_MASKED_CALC_FINISHED_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.DATA */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_DATA_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.DATA */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_DATA_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.DATA */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_128LO */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_128LO_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_128LO */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_128LO_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_128LO */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_128LO_OFF (1u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_128HI */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_128HI_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_128HI */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_128HI_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_128HI */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_128HI_OFF (2u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_256 */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_256_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_256 */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_256_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.AES_KEY_256 */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_AES_KEY_256_OFF (4u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.CLEAR_ALL */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_CLEAR_ALL_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.CLEAR_ALL */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_CLEAR_ALL_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_CLEAR_Bits.CLEAR_ALL */
#define IFX_MXAES_UNMASKED_USER_RANGE_CLEAR_CLEAR_ALL_OFF (5u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_BUS_COUNTER_Bits.CTR */
#define IFX_MXAES_UNMASKED_USER_RANGE_BUS_COUNTER_CTR_LEN (8u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_BUS_COUNTER_Bits.CTR */
#define IFX_MXAES_UNMASKED_USER_RANGE_BUS_COUNTER_CTR_MSK (0xffu)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_BUS_COUNTER_Bits.CTR */
#define IFX_MXAES_UNMASKED_USER_RANGE_BUS_COUNTER_CTR_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_Bits.QDENY_RESP */
#define IFX_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_QDENY_RESP_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_Bits.QDENY_RESP */
#define IFX_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_QDENY_RESP_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_Bits.QDENY_RESP */
#define IFX_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_QDENY_RESP_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_Bits.QDENY_STATUS */
#define IFX_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_QDENY_STATUS_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_Bits.QDENY_STATUS */
#define IFX_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_QDENY_STATUS_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_Bits.QDENY_STATUS */
#define IFX_MXAES_UNMASKED_USER_RANGE_QCHAN_CTL_QDENY_STATUS_OFF (1u)

/** \brief Length for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.Test0 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Test0_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.Test0 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Test0_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.Test0 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Test0_OFF (0u)

/** \brief Length for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.Test01 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Test01_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.Test01 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Test01_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.Test01 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Test01_OFF (1u)

/** \brief Length for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST10 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST10_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST10 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST10_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST10 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST10_OFF (2u)

/** \brief Length for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST101 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST101_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST101 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST101_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST101 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST101_OFF (5u)

/** \brief Length for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST110 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST110_LEN (1u)

/** \brief Mask for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST110 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST110_MSK (0x1u)

/** \brief Offset for Ifx_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_Bits.TEST110 */
#define IFX_MXAES_UNMASKED_INTERNAL_RANGE_TEST_1_TEST110_OFF (6u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_SEED_U_Bits.PRNG_SEED */
#define IFX_MXAES_MASKED_USER_RANGE_SEED_U_PRNG_SEED_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_SEED_U_Bits.PRNG_SEED */
#define IFX_MXAES_MASKED_USER_RANGE_SEED_U_PRNG_SEED_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_SEED_U_Bits.PRNG_SEED */
#define IFX_MXAES_MASKED_USER_RANGE_SEED_U_PRNG_SEED_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_0_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_0_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_0_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_0_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_0_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_0_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_1_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_1_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_1_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_1_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_1_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_1_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_2_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_2_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_2_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_2_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_2_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_2_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_3_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_3_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_3_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_3_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_3_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_3_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_4_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_4_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_4_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_4_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_4_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_4_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_5_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_5_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_5_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_5_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_5_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_5_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_6_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_6_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_6_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_6_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_6_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_6_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_7_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_7_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_7_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_7_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_0_7_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_0_7_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_0_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_0_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_0_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_0_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_0_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_0_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_1_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_1_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_1_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_1_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_1_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_1_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_2_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_2_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_2_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_2_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_2_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_2_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_3_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_3_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_3_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_3_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_3_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_3_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_4_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_4_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_4_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_4_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_4_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_4_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_5_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_5_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_5_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_5_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_5_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_5_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_6_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_6_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_6_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_6_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_6_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_6_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_7_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_7_KEY_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_7_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_7_KEY_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_KEY_1_7_Bits.KEY */
#define IFX_MXAES_MASKED_USER_RANGE_KEY_1_7_KEY_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_0_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_0_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_0_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_1_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_1_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_1_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_2_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_2_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_2_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_3_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_3_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_0_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_0_3_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_0_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_0_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_0_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_1_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_1_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_1_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_2_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_2_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_2_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_3_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_3_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_1_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_1_3_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_0_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_0_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_0_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_1_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_1_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_1_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_2_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_2_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_2_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_3_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_3_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_0_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_0_3_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_0_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_0_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_0_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_0_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_1_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_1_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_1_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_1_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_2_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_2_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_2_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_2_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_3_DATA_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_3_DATA_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_USER_RANGE_DATA_RR_1_3_Bits.DATA */
#define IFX_MXAES_MASKED_USER_RANGE_DATA_RR_1_3_DATA_OFF (0u)

/** \brief Length for Ifx_MXAES_MASKED_INTERNAL_RANGE_TEST_2_Bits.TEST */
#define IFX_MXAES_MASKED_INTERNAL_RANGE_TEST_2_TEST_LEN (32u)

/** \brief Mask for Ifx_MXAES_MASKED_INTERNAL_RANGE_TEST_2_Bits.TEST */
#define IFX_MXAES_MASKED_INTERNAL_RANGE_TEST_2_TEST_MSK (0xffffffffu)

/** \brief Offset for Ifx_MXAES_MASKED_INTERNAL_RANGE_TEST_2_Bits.TEST */
#define IFX_MXAES_MASKED_INTERNAL_RANGE_TEST_2_TEST_OFF (0u)

/** \}  */

/******************************************************************************/

/******************************************************************************/

#endif /* _IFXMXAES_BF_H_ */
