/***************************************************************************//**
* \file IfxPWRMODE_regdef.h
*
* \brief
* PWRMODE Registers
*
********************************************************************************
* \copyright
* (c) 2025-2026, Infineon Technologies AG or an affiliate of
* Infineon Technologies AG.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
********************************************************************************
*
* \defgroup IfxSfr_PWRMODE_Registers PWRMODE Registers
* \ingroup IfxSfr
* \defgroup IfxSfr_PWRMODE_Registers_Bitfields Bitfields
* \ingroup IfxSfr_PWRMODE_Registers
*
* \defgroup IfxSfr_PWRMODE_Registers_union Register unions
* \ingroup IfxSfr_PWRMODE_Registers
*
* \defgroup IfxSfr_PWRMODE_Registers_struct Memory map
* \ingroup IfxSfr_PWRMODE_Registers
*
*******************************************************************************/

#ifndef _IFXPWRMODE_REGDEF_H_
#define _IFXPWRMODE_REGDEF_H_ 1

/******************************************************************************/
#include "Ifx_TypesReg.h"
/******************************************************************************/

/******************************************************************************/

/******************************************************************************/


/** \addtogroup IfxSfr_PWRMODE_Registers_Bitfields
 * \{  */
/** \brief Clock Selection for Power Mode Components */
typedef struct _Ifx_PWRMODE_CLK_SELECT_Bits
{
    __IO Ifx_UReg_32Bit CLK_PWR_DIV:8;          /**< \brief [7:0]   clk_pwr is generated by dividing the
                                                                    CLK_PWR_MUX selection by (CLK_PWR_DIV+1). (rw) */
    __I  Ifx_UReg_32Bit :8;                     /**< \brief [15:8]  \internal Reserved */
    __IO Ifx_UReg_32Bit CLK_PWR_MUX:2;          /**< \brief [17:16] Selects a source for the clock used by
                                                                    power control components.
                                                                    Note that not all products support all clock sources.
                                                                    Selecting a clock source that is not supported will
                                                                    result in undefined behavior.
                                                                    It takes four cycles of the originally selected
                                                                    clock to switch away from it.
                                                                    Do not disable the original clock during this time. (rw)
                                                IMO           : 0u   IMO - Internal R/C Oscillator
                                                IHO           : 1u   IHO - Internal High-speed Oscillator
                                                RESERVED      : 2u   reserved */
    __I  Ifx_UReg_32Bit :14;                    /**< \brief [31:18] \internal Reserved */
} Ifx_PWRMODE_CLK_SELECT_Bits;

/* PWRMODE_CLK_SELECT.CLK_PWR_MUX enumerated values */

/** \brief IMO - Internal R/C Oscillator */
#define IFX_PWRMODE_CLK_SELECT_CLK_PWR_MUX_IMO (0u)

/** \brief IHO - Internal High-speed Oscillator */
#define IFX_PWRMODE_CLK_SELECT_CLK_PWR_MUX_IHO (1u)

/** \brief reserved */
#define IFX_PWRMODE_CLK_SELECT_CLK_PWR_MUX_RESERVED (2u)

/** \brief Dependency Sense Register */
typedef struct _Ifx_PWRMODE_PD_PD_SENSE_Bits
{
    __IO Ifx_UReg_32Bit PD_ON:16;               /**< \brief [15:0]  Each bit <i> indicates whether PD<j> is
                                                                    directly kept on when PD<i> is on.
                                                                    Indirect dependency is still possible if multiple
                                                                    direct dependencies work together to create a
                                                                    transitive relationship.
                                                                    For example, if PD1 depends upon PD2; and PD2
                                                                    dpends upon PD3; then PD1 indirectly depends upon
                                                                    PD3 regardless of whether there is a direct
                                                                    dependency from PD3 to PD1.
                                                                    Some bits are implemented as constants, and some
                                                                    bits are implemented as user-configurable registers.
                                                                    Refer to PD_SPT register to see how each bit is
                                                                    implemented. (rw) */
    __I  Ifx_UReg_32Bit :16;                    /**< \brief [31:16] \internal Reserved */
} Ifx_PWRMODE_PD_PD_SENSE_Bits;

/** \brief Dependency Support Register */
typedef struct _Ifx_PWRMODE_PD_PD_SPT_Bits
{
    __I  Ifx_UReg_32Bit PD_FORCE_ON:16;         /**< \brief [15:0]  Each bit <i> indicates whether PD<j> is
                                                                    always kept on when PD<i> is on for sense bits that
                                                                    are not configurable.
                                                                    For configurable bits, this indicates the reset
                                                                    value of the configurable bit. (r) */
    __I  Ifx_UReg_32Bit PD_CONFIG_ON:16;        /**< \brief [31:16] Each bit <i> indicates whether PD<j> can be
                                                                    configured on when PD<i> is on. (r) */
} Ifx_PWRMODE_PD_PD_SPT_Bits;

/** \brief Power Policy Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWPR_Bits
{
    __IO Ifx_UReg_32Bit PWR_POLICY:4;           /**< \brief [3:0]   Power mode policy.
                                                                    When static power mode transitions are enabled,
                                                                    PWR_DYN_EN is set to 0, this is the target power
                                                                    mode for the PPU.
                                                                    When dynamic power mode transitions are enabled,
                                                                    PWR_DYN_EN is set to 1, this is the minimum power
                                                                    mode for the PPU.
                                                                    This PPU supports the following modes: OFF(0),
                                                                    MEM_RET(2), FULL_RET(5), ON(8).
                                                                    Do not use WARM_RST(9) or other unsupported modes. (rw) */
    __I  Ifx_UReg_32Bit :4;                     /**< \brief [7:4]   \internal Reserved */
    __IO Ifx_UReg_32Bit PWR_DYN_EN:1;           /**< \brief [8:8]   Power mode dynamic transition enable.
                                                                    For main PPU, keep this bit 1. (rw) */
    __I  Ifx_UReg_32Bit :3;                     /**< \brief [11:9]  \internal Reserved */
    __IO Ifx_UReg_32Bit LOCK_EN:1;              /**< \brief [12:12] Reserved (rw) */
    __I  Ifx_UReg_32Bit :3;                     /**< \brief [15:13] \internal Reserved */
    __IO Ifx_UReg_32Bit OP_POLICY:4;            /**< \brief [19:16] Reserved (rw) */
    __I  Ifx_UReg_32Bit :4;                     /**< \brief [23:20] \internal Reserved */
    __IO Ifx_UReg_32Bit OP_DYN_EN:1;            /**< \brief [24:24] Reserved (rw) */
    __I  Ifx_UReg_32Bit :7;                     /**< \brief [31:25] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWPR_Bits;

/** \brief Power Mode Emulation Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PMER_Bits
{
    __IO Ifx_UReg_32Bit EMU_EN:1;               /**< \brief [0:0]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :31;                    /**< \brief [31:1]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PMER_Bits;

/** \brief Power Status Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWSR_Bits
{
    __I  Ifx_UReg_32Bit PWR_STATUS:4;           /**< \brief [3:0]   Power mode status.
                                                                    These bits reflect the current power mode of the PPU.
                                                                    See PPU_PWPR.PWR_POLICY for power mode enumeration. (r) */
    __I  Ifx_UReg_32Bit :4;                     /**< \brief [7:4]   \internal Reserved */
    __I  Ifx_UReg_32Bit PWR_DYN_STATUS:1;       /**< \brief [8:8]   Power mode dynamic transition status.
                                                                    When set to 1 power mode dynamic transitions are enabled.
                                                                    There might be a delay in dynamic transitions
                                                                    becoming active or inactive if the PPU is
                                                                    transitioning when PWR_DYN_EN is programmed. (r) */
    __I  Ifx_UReg_32Bit :3;                     /**< \brief [11:9]  \internal Reserved */
    __I  Ifx_UReg_32Bit LOCK_STATUS:1;          /**< \brief [12:12] Reserved (r) */
    __I  Ifx_UReg_32Bit :3;                     /**< \brief [15:13] \internal Reserved */
    __I  Ifx_UReg_32Bit OP_STATUS:4;            /**< \brief [19:16] Reserved (r) */
    __I  Ifx_UReg_32Bit :4;                     /**< \brief [23:20] \internal Reserved */
    __I  Ifx_UReg_32Bit OP_DYN_STATUS:1;        /**< \brief [24:24] Reserved (r) */
    __I  Ifx_UReg_32Bit :7;                     /**< \brief [31:25] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWSR_Bits;

/** \brief Device Interface Input Current Status Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DISR_Bits
{
    __I  Ifx_UReg_32Bit PWR_DEVACTIVE_STATUS:11; /**< \brief [10:0]  Status of the power mode DEVACTIVE inputs.
                                                                    There is one bit for each device interface
                                                                    Q-Channel DEVQACTIVE.
                                                                    For example, bit 0 is for Q-channel device 0 DEVQACTIVE.
                                                                    Refer to PPU_IDR0.DEVCHAN for device channel enumeration. (r) */
    __I  Ifx_UReg_32Bit :13;                    /**< \brief [23:11] \internal Reserved */
    __I  Ifx_UReg_32Bit OP_DEVACTIVE_STATUS:8;  /**< \brief [31:24] Reserved (r) */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DISR_Bits;

/** \brief Miscellaneous Input Current Status Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MISR_Bits
{
    __I  Ifx_UReg_32Bit PCSMPACCEPT_STATUS:1;   /**< \brief [0:0]   The status of the PCSMPACCEPT input. (r) */
    __I  Ifx_UReg_32Bit :7;                     /**< \brief [7:1]   \internal Reserved */
    __I  Ifx_UReg_32Bit DEVACCEPT_STATUS:8;     /**< \brief [15:8]  Status of the device interface DEVACCEPT inputs.
                                                                    There is one bit for each device interface DEVQACCEPTn.
                                                                    For example, bit 8 is for Q-Channel 0 DEVQACCEPTn
                                                                    and bit 9 for Q-Channel 1 DEVQACCEPTn.
                                                                    Refer to PPU_IDR0.DEVCHAN for device channel enumeration. (r) */
    __I  Ifx_UReg_32Bit DEVDENY_STATUS:8;       /**< \brief [23:16] Status of the device interface DEVDENY inputs.
                                                                    There is one bit for each device interface DEVQDENY.
                                                                    For example, bit 16 is for Q-Channel 0 DEVQDENY,
                                                                    and bit 17 for Q-Channel 1 DEVQDENY.
                                                                    Refer to PPU_IDR0.DEVCHAN for device channel enumeration. (r) */
    __I  Ifx_UReg_32Bit :8;                     /**< \brief [31:24] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MISR_Bits;

/** \brief Stored Status Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_STSR_Bits
{
    __I  Ifx_UReg_32Bit STORED_DEVDENY:8;       /**< \brief [7:0]   Status of the DEVDENY signals from the last
                                                                    device interface Q-Channel transition.
                                                                    For Q-Channel:  There is one bit for each device
                                                                    interface DEVQDENY.
                                                                    For example, bit 0 is for Q-Channel 0 DEVQDENY, and
                                                                    bit 1 for Q-Channel 1 DEVQDENY.
                                                                    Refer to PPU_DISR.PWR_DEVACTIVE_STATUS for device
                                                                    enumeration. (r) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_STSR_Bits;

/** \brief Unlock register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_UNLK_Bits
{
    __IO Ifx_UReg_32Bit UNLOCK:1;               /**< \brief [0:0]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :31;                    /**< \brief [31:1]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_UNLK_Bits;

/** \brief Power Configuration Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWCR_Bits
{
    __IO Ifx_UReg_32Bit DEVREQEN:8;             /**< \brief [7:0]   When set to 1 enables the device interface
                                                                    handshake for transitions.
                                                                    All available bits are reset to 1.
                                                                    There is one bit for each device interface channel.
                                                                    For example, bit 0 is for Q-Channel 0, and bit 1 is
                                                                    for Q-Channel 1.
                                                                    Refer to PPU_IDR0.DEVCHAN for device channel enumeration. (rw) */
    __IO Ifx_UReg_32Bit PWR_DEVACTIVEEN:11;     /**< \brief [18:8]  These bits enable the power mode DEVACTIVE inputs.
                                                                    When a bit is to 1 the related DEVACTIVE input is
                                                                    enabled, when set to 0 it is disabled.
                                                                    All available bits are reset to 1.
                                                                    There is one bit for each device interface
                                                                    Q-Channel DEVQACTIVE.
                                                                    For example, bit 8 is for the Q-Channel 0
                                                                    DEVQACTIVE, and bit 9 for the Q-Channel 1 DEVQACTIVE.
                                                                    Refer to PPU_IDR0.DEVCHAN for device channel enumeration. (rw) */
    __I  Ifx_UReg_32Bit :5;                     /**< \brief [23:19] \internal Reserved */
    __IO Ifx_UReg_32Bit OP_DEVACTIVEEN:8;       /**< \brief [31:24] Reserved (rw) */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWCR_Bits;

/** \brief Power Mode Transition Configuration Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PTCR_Bits
{
    __IO Ifx_UReg_32Bit WARM_RST_DEVREQEN:1;    /**< \brief [0:0]   Transition behavior between ON and WARM_RST.
                                                                    This bit should not be modified when the PPU is in
                                                                    WARM_RST, or if the PPU is performing a transition,
                                                                    otherwise PPU behavior is UNPREDICTABLE.
                                                                    0:  The PPU does not perform a device interface
                                                                    handshake when transitioning between ON and
                                                                    WARM_RST.
                                                                    1:  The PPU performs a device interface handshake
                                                                    when transitioning between ON and WARM_RST.
                                                                    This disables all Q-Channels for this transition. (rw) */
    __IO Ifx_UReg_32Bit DBG_RECOV_PORST_EN:1;   /**< \brief [1:1]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :30;                    /**< \brief [31:2]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PTCR_Bits;

/** \brief Interrupt Mask Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IMR_Bits
{
    __IO Ifx_UReg_32Bit STA_POLICY_TRN_IRQ_MASK:1; /**< \brief [0:0]   Static full policy transition completion
                                                                    event mask.
                                                                    For main PPU, this bit has no function because no
                                                                    static transitions are supported (see PWPR.PWR_DYN_EN). (rw) */
    __IO Ifx_UReg_32Bit STA_ACCEPT_IRQ_MASK:1;  /**< \brief [1:1]   Static transition acceptance event mask.
                                                                    For main PPU, keep this bit 1 to mask the event,
                                                                    otherwise the interrupt may trigger a wakeup. (rw) */
    __IO Ifx_UReg_32Bit STA_DENY_IRQ_MASK:1;    /**< \brief [2:2]   Static transition denial event mask. (rw) */
    __IO Ifx_UReg_32Bit EMU_ACCEPT_IRQ_MASK:1;  /**< \brief [3:3]   Reserved (rw) */
    __IO Ifx_UReg_32Bit EMU_DENY_IRQ_MASK:1;    /**< \brief [4:4]   Reserved (rw) */
    __IO Ifx_UReg_32Bit LOCKED_IRQ_MASK:1;      /**< \brief [5:5]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :26;                    /**< \brief [31:6]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IMR_Bits;

/** \brief Additional Interrupt Mask Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIMR_Bits
{
    __IO Ifx_UReg_32Bit UNSPT_POLICY_IRQ_MASK:1; /**< \brief [0:0]   Unsupported Policy event mask. (rw) */
    __IO Ifx_UReg_32Bit DYN_ACCEPT_IRQ_MASK:1;  /**< \brief [1:1]   Dynamic transition acceptance event mask.
                                                                    For main PPU, keep this bit 1 to mask the event,
                                                                    otherwise the interrupt that occurs when entering a
                                                                    low power mode may trigger a wakeup. (rw) */
    __IO Ifx_UReg_32Bit DYN_DENY_IRQ_MASK:1;    /**< \brief [2:2]   Dynamic transition denial event mask. (rw) */
    __IO Ifx_UReg_32Bit STA_POLICY_PWR_IRQ_MASK:1; /**< \brief [3:3]   Reserved (rw) */
    __IO Ifx_UReg_32Bit STA_POLICY_OP_IRQ_MASK:1; /**< \brief [4:4]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :27;                    /**< \brief [31:5]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIMR_Bits;

/** \brief Interrupt Status Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_ISR_Bits
{
    __IO Ifx_UReg_32Bit STA_POLICY_TRN_IRQ:1;   /**< \brief [0:0]   Static full policy transition completion
                                                                    event status. (rw) */
    __IO Ifx_UReg_32Bit STA_ACCEPT_IRQ:1;       /**< \brief [1:1]   Static transition acceptance event status. (rw) */
    __IO Ifx_UReg_32Bit STA_DENY_IRQ:1;         /**< \brief [2:2]   Static transition denial event status. (rw) */
    __IO Ifx_UReg_32Bit EMU_ACCEPT_IRQ:1;       /**< \brief [3:3]   Reserved (rw) */
    __IO Ifx_UReg_32Bit EMU_DENY_IRQ:1;         /**< \brief [4:4]   Reserved (rw) */
    __IO Ifx_UReg_32Bit LOCKED_IRQ:1;           /**< \brief [5:5]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [6:6]   \internal Reserved */
    __I  Ifx_UReg_32Bit OTHER_IRQ:1;            /**< \brief [7:7]   Indicates there is an interrupt event
                                                                    pending in the Additional Interrupt Status Register
                                                                    (PPU_AISR). (r) */
    __IO Ifx_UReg_32Bit PWR_ACTIVE_EDGE_IRQ:11; /**< \brief [18:8]  Indicates which power mode DEVACTIVE inputs
                                                                    caused the input edge event.
                                                                    Bits for unused channels are the MSBs and are reserved.
                                                                    There is one bit for each device Q-Channel DEVQACTIVE.
                                                                    For example, bit 8 is for the Q-Channel 0 DEVQACTIVE.
                                                                    Refer to PPU_IDR0.DEVCHAN for device channel enumeration. (rw) */
    __I  Ifx_UReg_32Bit :5;                     /**< \brief [23:19] \internal Reserved */
    __IO Ifx_UReg_32Bit OP_ACTIVE_EDGE_IRQ:8;   /**< \brief [31:24] Indicates which operating mode DEVPACTIVE
                                                                    inputs caused the input edge event.
                                                                    When operating modes are not supported this field
                                                                    is reserved. (rw) */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_ISR_Bits;

/** \brief Additional Interrupt Status Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AISR_Bits
{
    __IO Ifx_UReg_32Bit UNSPT_POLICY_IRQ:1;     /**< \brief [0:0]   Unsupported Policy event status. (rw) */
    __IO Ifx_UReg_32Bit DYN_ACCEPT_IRQ:1;       /**< \brief [1:1]   Dynamic transition acceptance event status. (rw) */
    __IO Ifx_UReg_32Bit DYN_DENY_IRQ:1;         /**< \brief [2:2]   Dynamic transition denial event status. (rw) */
    __IO Ifx_UReg_32Bit STA_POLICY_PWR_IRQ:1;   /**< \brief [3:3]   Reserved (rw) */
    __IO Ifx_UReg_32Bit STA_POLICY_OP_IRQ:1;    /**< \brief [4:4]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :27;                    /**< \brief [31:5]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AISR_Bits;

/** \brief Input Edge Sensitivity Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IESR_Bits
{
    __IO Ifx_UReg_32Bit DEVACTIVE00_EDGE:2;     /**< \brief [1:0]   DEVACTIVE 0 edge sensitivity. (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE01_EDGE:2;     /**< \brief [3:2]   DEVACTIVE 1 edge sensitivity. (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE02_EDGE:2;     /**< \brief [5:4]   DEVACTIVE 2 edge sensitivity. (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE03_EDGE:2;     /**< \brief [7:6]   Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE04_EDGE:2;     /**< \brief [9:8]   Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE05_EDGE:2;     /**< \brief [11:10] Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE06_EDGE:2;     /**< \brief [13:12] Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE07_EDGE:2;     /**< \brief [15:14] Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE08_EDGE:2;     /**< \brief [17:16] Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE09_EDGE:2;     /**< \brief [19:18] Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE10_EDGE:2;     /**< \brief [21:20] Reserved (rw) */
    __I  Ifx_UReg_32Bit :10;                    /**< \brief [31:22] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IESR_Bits;

/** \brief Operating Mode Active Edge Sensitivity Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_OPSR_Bits
{
    __IO Ifx_UReg_32Bit DEVACTIVE16_EDGE:2;     /**< \brief [1:0]   Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE17_EDGE:2;     /**< \brief [3:2]   Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE18_EDGE:2;     /**< \brief [5:4]   Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE19_EDGE:2;     /**< \brief [7:6]   Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE20_EDGE:2;     /**< \brief [9:8]   Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE21_EDGE:2;     /**< \brief [11:10] Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE22_EDGE:2;     /**< \brief [13:12] Reserved (rw) */
    __IO Ifx_UReg_32Bit DEVACTIVE23_EDGE:2;     /**< \brief [15:14] Reserved (rw) */
    __I  Ifx_UReg_32Bit :16;                    /**< \brief [31:16] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_OPSR_Bits;

/** \brief Functional Retention RAM Configuration Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FUNRR_Bits
{
    __IO Ifx_UReg_32Bit FUNC_RET_RAM_CFG:8;     /**< \brief [7:0]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FUNRR_Bits;

/** \brief Full Retention RAM Configuration Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FULRR_Bits
{
    __IO Ifx_UReg_32Bit FULL_RET_RAM_CFG:8;     /**< \brief [7:0]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FULRR_Bits;

/** \brief Memory Retention RAM Configuration Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MEMRR_Bits
{
    __IO Ifx_UReg_32Bit MEM_RET_RAM_CFG:8;      /**< \brief [7:0]   Reserved (rw) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MEMRR_Bits;

/** \brief Power Mode Entry Delay Register 0 */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR0_Bits
{
    __IO Ifx_UReg_32Bit OFF_DEL:8;              /**< \brief [7:0]   Reserved (rw) */
    __IO Ifx_UReg_32Bit MEM_RET_DEL:8;          /**< \brief [15:8]  Reserved (rw) */
    __IO Ifx_UReg_32Bit LOGIC_RET_DEL:8;        /**< \brief [23:16] Reserved (rw) */
    __IO Ifx_UReg_32Bit FULL_RET_DEL:8;         /**< \brief [31:24] Reserved (rw) */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR0_Bits;

/** \brief Power Mode Entry Delay Register 1 */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR1_Bits
{
    __IO Ifx_UReg_32Bit MEM_OFF_DEL:8;          /**< \brief [7:0]   Reserved (rw) */
    __IO Ifx_UReg_32Bit FUNC_RET_DEL:8;         /**< \brief [15:8]  Reserved (rw) */
    __I  Ifx_UReg_32Bit :16;                    /**< \brief [31:16] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR1_Bits;

/** \brief Device Control Delay Configuration Register 0 */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR0_Bits
{
    __I  Ifx_UReg_32Bit CLKEN_RST_DLY:8;        /**< \brief [7:0]   Reserved (r) */
    __I  Ifx_UReg_32Bit ISO_CLKEN_DLY:8;        /**< \brief [15:8]  Reserved (r) */
    __I  Ifx_UReg_32Bit RST_HWSTAT_DLY:8;       /**< \brief [23:16] Reserved (r) */
    __I  Ifx_UReg_32Bit :8;                     /**< \brief [31:24] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR0_Bits;

/** \brief Device Control Delay Configuration Register 1 */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR1_Bits
{
    __I  Ifx_UReg_32Bit ISO_RST_DLY:8;          /**< \brief [7:0]   Reserved (r) */
    __I  Ifx_UReg_32Bit CLKEN_ISO_DLY:8;        /**< \brief [15:8]  Reserved (r) */
    __I  Ifx_UReg_32Bit :16;                    /**< \brief [31:16] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR1_Bits;

/** \brief PPU Identification Register 0 */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR0_Bits
{
    __I  Ifx_UReg_32Bit DEVCHAN:4;              /**< \brief [3:0]   No. of Device Interface Channels.
                                                                    0: This is a P-Channel PPU.
                                                                    Refer to PPU_IDR1.OP_ACTIVE for the number of
                                                                    DEVPACTIVE inputs and their meaning.
                                                                    non-zero: The value is the number of Q-Channels.
                                                                    The device enumeration is:
                                                                    Device 0: PDCM (r) */
    __I  Ifx_UReg_32Bit NUM_OPMODE:4;           /**< \brief [7:4]   No. of operating modes supported is NUM_OPMODE + 1. (r) */
    __I  Ifx_UReg_32Bit STA_OFF_SPT:1;          /**< \brief [8:8]   OFF support. (r) */
    __I  Ifx_UReg_32Bit STA_OFF_EMU_SPT:1;      /**< \brief [9:9]   OFF_EMU support. (r) */
    __I  Ifx_UReg_32Bit STA_MEM_RET_SPT:1;      /**< \brief [10:10] MEM_RET support. (r) */
    __I  Ifx_UReg_32Bit STA_MEM_RET_EMU_SPT:1;  /**< \brief [11:11] MEM_RET_EMU support. (r) */
    __I  Ifx_UReg_32Bit STA_LGC_RET_SPT:1;      /**< \brief [12:12] LOGIC_RET support. (r) */
    __I  Ifx_UReg_32Bit STA_MEM_OFF_SPT:1;      /**< \brief [13:13] MEM_OFF support. (r) */
    __I  Ifx_UReg_32Bit STA_FULL_RET_SPT:1;     /**< \brief [14:14] FULL_RET support. (r) */
    __I  Ifx_UReg_32Bit STA_FUNC_RET_SPT:1;     /**< \brief [15:15] FUNC_RET support. (r) */
    __I  Ifx_UReg_32Bit STA_ON_SPT:1;           /**< \brief [16:16] ON support. (r) */
    __I  Ifx_UReg_32Bit STA_WRM_RST_SPT:1;      /**< \brief [17:17] WARM_RST support.  Ignore this bit.
                                                                    Do not use WARM_RST. (r) */
    __I  Ifx_UReg_32Bit STA_DBG_RECOV_SPT:1;    /**< \brief [18:18] DBG_RECOV support. (r) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [19:19] \internal Reserved */
    __I  Ifx_UReg_32Bit DYN_OFF_SPT:1;          /**< \brief [20:20] Dynamic OFF support. (r) */
    __I  Ifx_UReg_32Bit DYN_OFF_EMU_SPT:1;      /**< \brief [21:21] Dynamic OFF_EMU support. (r) */
    __I  Ifx_UReg_32Bit DYN_MEM_RET_SPT:1;      /**< \brief [22:22] Dynamic MEM_RET support. (r) */
    __I  Ifx_UReg_32Bit DYN_MEM_RET_EMU_SPT:1;  /**< \brief [23:23] Dynamic MEM_RET_EMU support (r) */
    __I  Ifx_UReg_32Bit DYN_LGC_RET_SPT:1;      /**< \brief [24:24] Dynamic LOGIC_RET support. (r) */
    __I  Ifx_UReg_32Bit DYN_MEM_OFF_SPT:1;      /**< \brief [25:25] Dynamic MEM_OFF support. (r) */
    __I  Ifx_UReg_32Bit DYN_FULL_RET_SPT:1;     /**< \brief [26:26] Dynamic FULL_RET support. (r) */
    __I  Ifx_UReg_32Bit DYN_FUNC_RET_SPT:1;     /**< \brief [27:27] Dynamic FUNC_RET support. (r) */
    __I  Ifx_UReg_32Bit DYN_ON_SPT:1;           /**< \brief [28:28] Dynamic ON support. (r) */
    __I  Ifx_UReg_32Bit DYN_WRM_RST_SPT:1;      /**< \brief [29:29] Dynamic WARM_RST support. (r) */
    __I  Ifx_UReg_32Bit :2;                     /**< \brief [31:30] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR0_Bits;

/** \brief PPU Identification Register 1 */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR1_Bits
{
    __I  Ifx_UReg_32Bit PWR_MODE_ENTRY_DEL_SPT:1; /**< \brief [0:0]   Power mode entry delay support. (r) */
    __I  Ifx_UReg_32Bit SW_DEV_DEL_SPT:1;       /**< \brief [1:1]   Software device delay control configuration
                                                                    support. (r) */
    __I  Ifx_UReg_32Bit LOCK_SPT:1;             /**< \brief [2:2]   Lock and the lock interrupt event are supported. (r) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [3:3]   \internal Reserved */
    __I  Ifx_UReg_32Bit MEM_RET_RAM_REG:1;      /**< \brief [4:4]   Indicates if the PPU_MEMRR register is
                                                                    present or reserved.  0: Reserved.  1: Present. (r) */
    __I  Ifx_UReg_32Bit FULL_RET_RAM_REG:1;     /**< \brief [5:5]   Indicates if the PPU_FULRR register is
                                                                    present or reserved.  0: Reserved.  1: Present. (r) */
    __I  Ifx_UReg_32Bit FUNC_RET_RAM_REG:1;     /**< \brief [6:6]   Indicates if the PPU_FUNRR register is
                                                                    present or reserved.  0: Reserved.  1: Present. (r) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [7:7]   \internal Reserved */
    __I  Ifx_UReg_32Bit STA_POLICY_PWR_IRQ_SPT:1; /**< \brief [8:8]   Power policy transition completion event status. (r) */
    __I  Ifx_UReg_32Bit STA_POLICY_OP_IRQ_SPT:1; /**< \brief [9:9]   Operating policy transition completion
                                                                    event status. (r) */
    __I  Ifx_UReg_32Bit OP_ACTIVE:1;            /**< \brief [10:10] Operating mode use model for dynamic transitions.
                                                                    0: Ladder use model.  1: Independent use model.
                                                                    When operating modes are not supported
                                                                    (PPU_IDR0.NUM_OPMODE==0), this field is reserved. (r) */
    __I  Ifx_UReg_32Bit :1;                     /**< \brief [11:11] \internal Reserved */
    __I  Ifx_UReg_32Bit OFF_MEM_RET_TRANS:1;    /**< \brief [12:12] OFF to MEM_RET direct transition.
                                                                    Indicates if direct transitions from OFF to MEM_RET
                                                                    and from OFF_EMU to MEM_RET_EMU are supported. (r) */
    __I  Ifx_UReg_32Bit :19;                    /**< \brief [31:13] \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR1_Bits;

/** \brief Implementation Identification Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IIDR_Bits
{
    __I  Ifx_UReg_32Bit IMPLEMENTER:12;         /**< \brief [11:0]  Implementer identification.
                                                                    [11:8] The JEP106 continuation code of the implementer.
                                                                    [7] Always 0.
                                                                    [6:0] The JEP106 identity code of the implementer.
                                                                    For an Arm implementation, bits [11:0] are 0x43B. (r) */
    __I  Ifx_UReg_32Bit REVISION:4;             /**< \brief [15:12] Minor revision of the product. (r) */
    __I  Ifx_UReg_32Bit VARIANT:4;              /**< \brief [19:16] Major revision of the product. (r) */
    __I  Ifx_UReg_32Bit PRODUCT_ID:12;          /**< \brief [31:20] PPU part identification. (r) */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IIDR_Bits;

/** \brief Architecture Identification Register */
typedef struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIDR_Bits
{
    __I  Ifx_UReg_32Bit ARCH_REV_MINOR:4;       /**< \brief [3:0]   0x1 - PPU Architecture minor revision 1.
                                                                    Other Values - Reserved. (r) */
    __I  Ifx_UReg_32Bit ARCH_REV_MAJOR:4;       /**< \brief [7:4]   0x1 - PPU architecture major revision 1.
                                                                    Other Values - Reserved. (r) */
    __I  Ifx_UReg_32Bit :24;                    /**< \brief [31:8]  \internal Reserved */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIDR_Bits;


/** \}  */
/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_PWRMODE_Registers_union
 * \{   */
/** \brief Clock Selection for Power Mode Components */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_CLK_SELECT_Bits B;              /**< \brief Bitfield access */
} Ifx_PWRMODE_CLK_SELECT;

/** \brief Dependency Sense Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PD_PD_SENSE_Bits B;             /**< \brief Bitfield access */
} Ifx_PWRMODE_PD_PD_SENSE;

/** \brief Dependency Support Register */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PD_PD_SPT_Bits B;               /**< \brief Bitfield access */
} Ifx_PWRMODE_PD_PD_SPT;

/** \brief Power Policy Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWPR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWPR;

/** \brief Power Mode Emulation Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PMER_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PMER;

/** \brief Power Status Register */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWSR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWSR;

/** \brief Device Interface Input Current Status Register */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DISR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DISR;

/** \brief Miscellaneous Input Current Status Register */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MISR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MISR;

/** \brief Stored Status Register */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_STSR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_STSR;

/** \brief Unlock register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_UNLK_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_UNLK;

/** \brief Power Configuration Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWCR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWCR;

/** \brief Power Mode Transition Configuration Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PTCR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PTCR;

/** \brief Interrupt Mask Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IMR_Bits B;   /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IMR;

/** \brief Additional Interrupt Mask Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIMR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIMR;

/** \brief Interrupt Status Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_ISR_Bits B;   /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_ISR;

/** \brief Additional Interrupt Status Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AISR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AISR;

/** \brief Input Edge Sensitivity Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IESR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IESR;

/** \brief Operating Mode Active Edge Sensitivity Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_OPSR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_OPSR;

/** \brief Functional Retention RAM Configuration Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FUNRR_Bits B; /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FUNRR;

/** \brief Full Retention RAM Configuration Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FULRR_Bits B; /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FULRR;

/** \brief Memory Retention RAM Configuration Register */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MEMRR_Bits B; /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MEMRR;

/** \brief Power Mode Entry Delay Register 0 */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR0_Bits B; /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR0;

/** \brief Power Mode Entry Delay Register 1 */
typedef union
{
    __IO Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __IO Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR1_Bits B; /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR1;

/** \brief Device Control Delay Configuration Register 0 */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR0_Bits B; /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR0;

/** \brief Device Control Delay Configuration Register 1 */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR1_Bits B; /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR1;

/** \brief PPU Identification Register 0 */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR0_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR0;

/** \brief PPU Identification Register 1 */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR1_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR1;

/** \brief Implementation Identification Register */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IIDR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IIDR;

/** \brief Architecture Identification Register */
typedef union
{
    __I  Ifx_UReg_32Bit U;                      /**< \brief Unsigned access */
    __I  Ifx_UReg_32Bit I;                      /**< \brief Signed access */
    Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIDR_Bits B;  /**< \brief Bitfield access */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIDR;


/** \}  */

/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_PWRMODE_PD_struct
 * \{  */
/******************************************************************************/
/** \name Object L1
 * \{  */
/** \brief PD object */
typedef volatile struct _Ifx_PWRMODE_PD
{
       __IO Ifx_PWRMODE_PD_PD_SENSE             PD_SENSE;               /**< \brief 0, Dependency Sense Register*/
       __I  Ifx_PWRMODE_PD_PD_SPT               PD_SPT;                 /**< \brief 4, Dependency Support Register*/
       __I  Ifx_UReg_8Bit                       reserved_8[8];          /**< \brief 8, */
} Ifx_PWRMODE_PD;

/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_PWRMODE_PPU_MAIN_PPU_MAIN_struct
 * \{  */
/******************************************************************************/
/** \name Object L2
 * \{  */
/** \brief PPU_MAIN object */
typedef volatile struct _Ifx_PWRMODE_PPU_MAIN_PPU_MAIN
{
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWPR  PWPR;                   /**< \brief 0, Power Policy Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PMER  PMER;                   /**< \brief 4, Power Mode Emulation Register*/
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWSR  PWSR;                   /**< \brief 8, Power Status Register*/
       __I  Ifx_UReg_8Bit                       reserved_C[4];          /**< \brief C, */
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DISR  DISR;                   /**< \brief 10, Device Interface Input Current Status Register*/
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MISR  MISR;                   /**< \brief 14, Miscellaneous Input Current Status Register*/
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_STSR  STSR;                   /**< \brief 18, Stored Status Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_UNLK  UNLK;                   /**< \brief 1C, Unlock register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PWCR  PWCR;                   /**< \brief 20, Power Configuration Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_PTCR  PTCR;                   /**< \brief 24, Power Mode Transition Configuration Register*/
       __I  Ifx_UReg_8Bit                       reserved_28[8];         /**< \brief 28, */
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IMR   IMR;                    /**< \brief 30, Interrupt Mask Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIMR  AIMR;                   /**< \brief 34, Additional Interrupt Mask Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_ISR   ISR;                    /**< \brief 38, Interrupt Status Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AISR  AISR;                   /**< \brief 3C, Additional Interrupt Status Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IESR  IESR;                   /**< \brief 40, Input Edge Sensitivity Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_OPSR  OPSR;                   /**< \brief 44, Operating Mode Active Edge Sensitivity Register*/
       __I  Ifx_UReg_8Bit                       reserved_48[8];         /**< \brief 48, */
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FUNRR FUNRR;                  /**< \brief 50, Functional Retention RAM Configuration Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_FULRR FULRR;                  /**< \brief 54, Full Retention RAM Configuration Register*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_MEMRR MEMRR;                  /**< \brief 58, Memory Retention RAM Configuration Register*/
       __I  Ifx_UReg_8Bit                       reserved_5C[260];       /**< \brief 5C, */
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR0 EDTR0;                  /**< \brief 160, Power Mode Entry Delay Register 0*/
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_EDTR1 EDTR1;                  /**< \brief 164, Power Mode Entry Delay Register 1*/
       __I  Ifx_UReg_8Bit                       reserved_168[8];        /**< \brief 168, */
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR0 DCDR0;                  /**< \brief 170, Device Control Delay Configuration Register 0*/
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_DCDR1 DCDR1;                  /**< \brief 174, Device Control Delay Configuration Register 1*/
       __I  Ifx_UReg_8Bit                       reserved_178[3640];     /**< \brief 178, */
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR0  IDR0;                   /**< \brief FB0, PPU Identification Register 0*/
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IDR1  IDR1;                   /**< \brief FB4, PPU Identification Register 1*/
       __I  Ifx_UReg_8Bit                       reserved_FB8[16];       /**< \brief FB8, */
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_IIDR  IIDR;                   /**< \brief FC8, Implementation Identification Register*/
       __I  Ifx_PWRMODE_PPU_MAIN_PPU_MAIN_AIDR  AIDR;                   /**< \brief FCC, Architecture Identification Register*/
       __I  Ifx_UReg_8Bit                       reserved_FD0[48];       /**< \brief FD0, */
} Ifx_PWRMODE_PPU_MAIN_PPU_MAIN;

/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_PWRMODE_PPU_MAIN_struct
 * \{  */
/******************************************************************************/
/** \name Object L1
 * \{  */
/** \brief PPU_MAIN object */
typedef volatile struct _Ifx_PWRMODE_PPU_MAIN
{
       __IO Ifx_PWRMODE_PPU_MAIN_PPU_MAIN       PPU_MAIN;               /**< \brief 0, Power Policy Unit Registers for the main power domain (VCCACT_PD)*/
} Ifx_PWRMODE_PPU_MAIN;

/******************************************************************************/
/******************************************************************************/
/** \addtogroup IfxSfr_PWRMODE_struct
 * \{  */
/******************************************************************************/
/** \name Object L0
 * \{  */
/** \brief PWRMODE object */
typedef volatile struct _Ifx_PWRMODE
{
       __IO Ifx_PWRMODE_PD                      PD[16];                 /**< \brief 0, Power Domain Dependency Sense Register*/
       __I  Ifx_UReg_8Bit                       reserved_100[3840];     /**< \brief 100, */
       __IO Ifx_PWRMODE_PPU_MAIN                PPU_MAIN;               /**< \brief 1000, Power Policy Unit for Active Domain*/
       __IO Ifx_PWRMODE_CLK_SELECT              CLK_SELECT;             /**< \brief 2000, Clock Selection for Power Mode Components*/
       __I  Ifx_UReg_8Bit                       reserved_2004[57340];   /**< \brief 2004, */
} Ifx_PWRMODE;

/******************************************************************************/

/******************************************************************************/

#endif /* _IFXPWRMODE_REGDEF_H_ */
